INCLUDES = -I$(top_srcdir)/include
CFLAGS = $(INCLUDES) -std=c99 -fPIC -ggdb -D__$(OSARCH)__ -nostartfiles -DHAVE_CONFIG_H
MODULES_INSTALL_PATH = $(top_srcdir)/bin/modules

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<

%.so: %.o
	$(CC) $(SOLINK) $(LDFLAGS) -o $@ $<

clean:
	rm -f *.so *.o
	rm -f $(top_srcdir)/bin/modules/*.so

install: all
	cp *.so $(MODULES_INSTALL_PATH) 
